= Java 8 (repeated) function call support
Jan Pollmann <pollmannjanf@gmail.com>
:compat-mode!:
:url-org: https://github.com/JanPollmann
:url-repo: {url-org}/Watchdog
:url-rel-file-base: link:
:url-rel-tree-base: link:
ifdef::env-github[]
:url-rel-file-base: {url-repo}/blob/HEAD/
:url-rel-tree-base: {url-repo}/tree/HEAD/
endif::[]
:path-example-1-FastLoopApp: Tester/src/main/java/de/pollmann/watchdog/tester/app/FastLoopApp.java
:path-example-1-AppContext: Tester/src/main/java/de/pollmann/watchdog/tester/app/AppContext.java
:path-test: Library/src/test/java/de/pollmann/watchdog/
:path-test-sabotage: Library/src/test/java/de/pollmann/watchdog/SabotageTest.java
:url-create-github-token: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
:url-packages: {url-repo}/packages

Each function call has a timeout and terminates the execution. After each function call (even after a timeout or an exception) a `TaskResult` is created with one of the following `ResultCode`:

* `ResultCode.OK` The execution is completed without exception and the result can be obtained with `TaskResult#getResult`
* `ResultCode.TIMEOUT` The function call was *NOT* completed, the task was canceled
* ResultCode.ERROR` An unexpected exception has occurred. The exception can be determined with `TaskResult#getErrorReason`.

== Quick start
This library supports `Runnable`, `Callable`, `Consumer` and `Function`. When a timeout occurs, the worker thread is `interrupted`. Be careful to handle the interruption properly, otherwise a thread of an `ExecutorService` (=> your function) could end up in an infinite loop (=> examples). One way to handle an interruption is as follows:
[source, java]
----
if (Thread.interrupted()) {
  throw new InterruptedException();
}
----

=== Setup
1. Import the `Library` in your project (see instructions below)
2. Create & store a `WatchdogFactory`. Each factory stores two `ExecutorServices`
3. Use `Watchable.builder(...)` to create a watchable and `WatchableOptions.builder(...)` to create the options +
_optional_: add a `ResultProcessor` to the watchable builder *(this callback not monitored)* +
4. Create an asynchronous function call with `WatchdogFactory#submitFunctionCall`, a synchronized function call using `WatchdogFactory#waitForCompletion` or create a `RepeatableTask` with `WatchdogFactory#createRepeated`
5. In case of a RepeatableTask call the task with `RepeatableTask#submitFunctionCall` and `RepeatableTask#waitForCompletion`

=== Import the Library
==== Gradle
[source]
----
repositories {
    maven {
        url = uri("https://maven.pkg.github.com/JanPollmann/Watchdog")
    }
}

dependencies {
    implementation 'de.pollmann.watchdog:watchdog:<version>'
}
----

==== Maven
Follow the GitHub documentation of the desired package:
{url-packages}

=== Important
[CAUTION]
====
* Please remind: `ResultProcessor` (if specified) will be called *after* the monitored function call *without any timeout*. If there is heavy computational work, the call will take longer as specified (or will not terminate if there is an infinite loop)
** Obviously, you could execute a `RepeatableTask` as `ResultProcessor` :)
* The timeout is specified in milliseconds
** A timeout of 0 ms will be handled as `no timeout`
* For not repeated function calls, the input of a function/consumer is passed to the builder!
* As soon as the internal worker of the `WatchdogFactory` gets garbage collected, `ExecutorServices#shutdown` is called for every `ExecutorServices` (finalize)
** A `RepeatableTask` has a reference to the internal worker
** To terminate the RepeatableTask call `RepeatableTask#terminate`
** A terminated RepeatableTask will throw a `RepeatableTaskTerminatedException`!
====


== Changelog
include::CHANGELOG.adoc[]

== Example
Just implement `loop`. Remarks:

* A timeout of 0 ms will be handled as `no timeout`
* both tasks have a `ResultConsumer` registered, but that's an optional feature

ifdef::env-github[]
{url-rel-file-base}{path-example-1-FastLoopApp}
endif::[]
ifndef::env-github[]
[source, java]
----
include::{path-example-1-FastLoopApp}[]
----
endif::[]

terminate endless loop
ifdef::env-github[]
{url-rel-file-base}{path-test-sabotage}
endif::[]
ifndef::env-github[]
[source, java]
----
include::{path-test-sabotage}[]
----
endif::[]

You can find more examples in the UnitTests: +
ifdef::env-github[]
{url-rel-file-base}{path-test}
endif::[]
ifndef::env-github[]
{path-test}
endif::[]
