= Java (repeated) function call support
Jan Pollmann <pollmannjanf@gmail.com>
:compat-mode!:
:url-org: https://github.com/JanPollmann
:url-repo: {url-org}/Watchdog
:url-rel-file-base: link:
:url-rel-tree-base: link:
ifdef::env-github[]
:url-rel-file-base: {url-repo}/blob/HEAD/
:url-rel-tree-base: {url-repo}/tree/HEAD/
endif::[]
:path-example-1-FastLoopApp: Tester/src/main/java/de/pollmann/watchdog/tester/app/FastLoopApp.java
:path-example-1-AppContext: Tester/src/main/java/de/pollmann/watchdog/tester/app/AppContext.java

Each function call has a timeout and terminates the execution. After each function call (even after a timeout or an exception) a `TaskResult` is created with on of the following `ResultCode`:

* `ResultCode.OK` The execution is completed without exception & the result can be obtained with `TaskResult#getResult`
* `ResultCode.TIMEOUT` The function call was *NOT* completed, the task was canceled
* `ResultCode.ERROR` An unexpected exception occurred. The exception can be obtained with `TaskResult#getErrorReason`

== Quick start
This library supports `Runnable`, `Callable`, `Consumer` and `Function`

=== How to
TODO publishing

=== Setup
1. Import the `Library` in your project
2. Create & store a `WatchdogFactory`. Each factory stores two `ExecutorServices`
3. create an asynchronous function call with `WatchdogFactory#submitFunctionCall`, a synchronized function call using `WatchdogFactory#waitForCompletion` or create a `RepeatableTask` with `WatchdogFactory#createRepeated`

=== Important
[CAUTION]
====
* As soon as the internal worker of the `WatchdogFactory` gets garbage collected, `ExecutorServices#shutdown` is called for every `ExecutorServices` (finalize)
** a `RepeatableTask` has a reference to the internal worker
** to terminate the RepeatableTask call `RepeatableTask#terminate`
** a terminated RepeatableTask will throw a `RepeatableTaskTerminatedException`!
* The timeout is specified in milliseconds
** a timeout of 0 ms will be handled as `no timeout`
====

== Example
Just implement `loop` +
Remark: A timeout of 0 ms will be handled as `no timeout`
ifdef::env-github[]
{url-rel-file-base}{path-example-1-FastLoopApp}
endif::[]
ifndef::env-github[]
[source, java]
----
include::{path-example-1-FastLoopApp}[]
----
endif::[]

Possible `AppContext` with a separated `WachdogFactory` for the whole application (not required).
ifdef::env-github[]
{url-rel-file-base}{path-example-1-AppContext}
endif::[]
ifndef::env-github[]
[source, java]
----
include::{path-example-1-AppContext}[]
----
endif::[]

